plugins:
  story_builder_enabled:
    default: false
    client: true
  story_source_url:
    default: "https://api.mercistory.com"
    client: false
  story_api_key:
    default: ""
    client: false
  story_sync_topics:
    default: true
    client: true
  story_sync_users:
    default: true
    client: true
  story_sync_interval:
    default: 1440
    client: false
  story_sync_immediately:
    default: true
    client: true
  story_allowed_categories:
    default: ""
    client: false
    type: list
    list_type: category 